parameters:
- name: app
  type: string
  displayName: "app"

stages:
- stage: Dev
#  condition: or(or(eq(variables['build.SourceBranchName'], 'develop'), contains(variables['build.SourceBranch'], 'feature'), startsWith(variables['build.SourceBranch'], 'hotfix'))
  condition: or(eq(variables['build.SourceBranchName'], 'develop'),contains(variables['build.SourceBranch'], 'feature'))
  variables:
  - group: ${{ parameters.app }}-dev
  jobs:
  - job: dev_cd
    steps:
    - template: template-frontend-deploy.yaml
    - script: |
        echo "Clearing npm cache..."
        rm -rf /home/azureuser/.npm/_cacache/
      displayName: 'Clear npm cache'

- stage: QA
  condition: contains(variables['build.SourceBranch'], 'release')
  variables:
  - group: ${{ parameters.app }}-qa
  jobs:
  - job: qa_cd
    steps:
    - template: template-frontend-deploy.yaml


- stage: SIT_Approval
  dependsOn: QA
  condition: succeeded('QA')
  jobs:
  - deployment: SIT_Approval
    displayName: SIT_approval 
    environment: SIT

- stage: SIT
  condition: succeeded('SIT_Approval') 
  variables:
  - group: ${{ parameters.app }}-sit
  jobs:
  - job: sit_cd
    steps:
    - template: template-frontend-deploy.yaml


- stage: UAT_Approval
  dependsOn: SIT
  condition: succeeded('SIT')
  jobs:
  - deployment: UAT_Approval
    displayName: UAT_approval 
    environment: UAT

- stage: UAT
  dependsOn: UAT_Approval
  condition: succeeded('UAT_Approval') 
  variables:
  - group: ${{ parameters.app }}-uat
  jobs:
  - job: uat_cd
    steps:
    - template: template-frontend-deploy.yaml


- stage: Prod_Approval
  dependsOn: UAT
  condition: succeeded('UAT')
  jobs:
  - deployment: Prod_Approval
    displayName: Prod_Approval 
    environment: prod

- stage: Prod
  dependsOn: Prod_Approval
  condition: succeeded('Prod_Approval')  
  variables:
  - group: ${{ parameters.app }}-prod
  jobs:
  - job: prod_cd
    steps:
    - template: template-frontend-deploy.yaml
      parameters:
        isProd: true
